# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
next_permutation <- function(x) {
    .Call('itercombin_next_permutation', PACKAGE = 'itercombin', x)
}

#' @export
next_combination <- function(x, r) {
    .Call('itercombin_next_combination', PACKAGE = 'itercombin', x, r)
}

