# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

next_combination <- function(x, n) {
    .Call('itercombin_next_combination', PACKAGE = 'itercombin', x, n)
}

all_combinations <- function(x_, n, d) {
    .Call('itercombin_all_combinations', PACKAGE = 'itercombin', x_, n, d)
}

next_multiset_combination <- function(multiset, x) {
    .Call('itercombin_next_multiset_combination', PACKAGE = 'itercombin', multiset, x)
}

all_multiset_combinations <- function(multiset, x_, d) {
    .Call('itercombin_all_multiset_combinations', PACKAGE = 'itercombin', multiset, x_, d)
}

#' Calculate mulinomial coefficient
#' @param n a vector of group sizes
#' @return multinomial coefficient
#' @details This function calculate the multinomial coefficient \deqn{\frac{(\sum n_j)!}{\prod n_j!}.}{(\sum n_j)! / \prod n_j!.}
#' 
#' Overflow error will be thrown if the return value is larger than the maximum limit of an unsigned long long variable.
#' @examples
#' # (3+1+1)!/ (3! 1! 1!) = 20
#' multichoose(c(3,1,1))
#' @export
multichoose <- function(n) {
    .Call('itercombin_multichoose', PACKAGE = 'itercombin', n)
}

next_permutation <- function(x) {
    .Call('itercombin_next_permutation', PACKAGE = 'itercombin', x)
}

all_permutations <- function(x_, d) {
    .Call('itercombin_all_permutations', PACKAGE = 'itercombin', x_, d)
}

next_k_permutation <- function(x, r) {
    .Call('itercombin_next_k_permutation', PACKAGE = 'itercombin', x, r)
}

all_k_permutations <- function(x_, r, d) {
    .Call('itercombin_all_k_permutations', PACKAGE = 'itercombin', x_, r, d)
}

