# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Permutation generation
#' 
#' Generate next permutation
#' @param x an integer-valued permutation vector
#' @return next permutation vector
#' @export
next_permutation <- function(x) {
    .Call('itercombin_next_permutation', PACKAGE = 'itercombin', x)
}

